# Generated by Django 5.1.4 on 2024-12-24 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='1. Admin, 2. Sub Admin, 3. User, 4. Others', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='1. Admin, 2. Sub Admin, 3. User, 4. Others', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
    ]
